apiVersion: v1
kind: Service
metadata:
  name: people-manage-web-service
  namespace: cqdev
  labels:
    app: people-manage-web-service
spec:
  type: NodePort
  ports:
    - port: 9001
      targetPort: 80
      nodePort: 30140
  selector:
    app: people-manage-web
